### ISSUE TITLE
Use Markdown formatting on README.md

### ISSUE THREAD

**Issue by nicksuch** [stockdalemark1978/stockdalemark1978.github.io#1]
Nice work getting all your links into the README, and getting it all pushed to GitHub! One thing you could improve is using Markdown instead of HTML formatting for your content. Check out how I did [my README](https://github.com/nicksuch/nicksuch.github.io/blob/master/README.md) as an example (clicking the `Raw` button may help you see my actual code), and see the [Markdown Syntax reference](https://daringfireball.net/projects/markdown/syntax), specifically for Lists and Links.

We'll use Markdown for blog posts during the Bootcamp, and it will show a little more nicely than your current HTML in your github repository.

**Comment by stockdalemark1978** [comment]
I noticed earlier this week that I'd done it incorrectly. I'm working on getting it all straightened out. I'll check out your example. Thanks for the feedback!

**Comment by stockdalemark1978** [comment]
I think I've got it now.
